# Generated by Django 2.1 on 2019-07-22 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Title')),
                ('description', models.TextField(max_length=200, verbose_name='Description')),
                ('author', models.CharField(blank=True, max_length=50, null=True, verbose_name='Author')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time of creation')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Start time')),
                ('ended_at', models.DateTimeField(auto_now_add=True, verbose_name='End time')),
                ('performer', models.CharField(blank=True, default='Unknown', max_length=50, null=True, verbose_name='Performed by')),
            ],
        ),
        migrations.CreateModel(
            name='IssueStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Issue status')),
            ],
        ),
        migrations.CreateModel(
            name='IssueType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Issue type')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_statuses', to='webapp.IssueStatus', verbose_name='Issue status'),
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_types', to='webapp.IssueType', verbose_name='Issue type'),
        ),
    ]
