# Generated by Django 2.1 on 2019-07-25 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20190725_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='milestone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='webapp.Milestone', verbose_name='Milestone'),
        ),
    ]
